import type { City, Category } from '$lib/types';
import type { Listing } from '$lib/types';

// Mock data for development without PostgreSQL
export const mockCities: City[] = [
	{
		id: 1,
		name: 'Тбилиси',
		slug: 'tbilisi',
		country: 'GE',
		imageUrl: null,
		listingsCount: 8,
		createdAt: new Date()
	},
	{
		id: 2,
		name: 'Батуми',
		slug: 'batumi',
		country: 'GE',
		imageUrl: null,
		listingsCount: 4,
		createdAt: new Date()
	},
	{
		id: 3,
		name: 'Кутаиси',
		slug: 'kutaisi',
		country: 'GE',
		imageUrl: null,
		listingsCount: 0,
		createdAt: new Date()
	},
	{
		id: 4,
		name: 'Рустави',
		slug: 'rustavi',
		country: 'GE',
		imageUrl: null,
		listingsCount: 0,
		createdAt: new Date()
	},
	{
		id: 5,
		name: 'Зугдиди',
		slug: 'zugdidi',
		country: 'GE',
		imageUrl: null,
		listingsCount: 0,
		createdAt: new Date()
	}
];

export const mockCategories: Category[] = [
	{ id: 1, name: 'Электроника', slug: 'electronics', icon: '📱', sortOrder: 1, createdAt: new Date() },
	{ id: 2, name: 'Одежда', slug: 'clothing', icon: '👕', sortOrder: 2, createdAt: new Date() },
	{ id: 3, name: 'Авто', slug: 'auto', icon: '🚗', sortOrder: 3, createdAt: new Date() },
	{ id: 4, name: 'Мебель', slug: 'furniture', icon: '🛋️', sortOrder: 4, createdAt: new Date() },
	{ id: 5, name: 'Недвижимость', slug: 'realestate', icon: '🏠', sortOrder: 5, createdAt: new Date() },
	{ id: 6, name: 'Услуги', slug: 'services', icon: '🔧', sortOrder: 6, createdAt: new Date() },
	{ id: 7, name: 'Детские товары', slug: 'kids', icon: '🧸', sortOrder: 7, createdAt: new Date() },
	{ id: 8, name: 'Спорт', slug: 'sport', icon: '⚽', sortOrder: 8, createdAt: new Date() },
	{ id: 9, name: 'Другое', slug: 'other', icon: '📦', sortOrder: 99, createdAt: new Date() }
];

type MockListing = Listing & { city: City; category: Category; telegramGroup?: null };

export const mockListings: MockListing[] = [
	{
		id: 1,
		telegramMessageId: null,
		telegramGroupId: 1,
		cityId: 1,
		categoryId: 1,
		title: 'iPhone 15 Pro Max 256GB',
		description: 'Продаю iPhone 15 Pro Max, состояние идеальное. Полный комплект: коробка, зарядка, чехол. Куплен в официальном магазине 3 месяца назад. Гарантия до сентября 2026.',
		price: '2800.00',
		currency: 'GEL',
		contact: '@seller_iphone',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=iPhone+15+Pro'],
		status: 'active',
		publishedAt: new Date(Date.now() - 2 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[0],
		category: mockCategories[0]
	},
	{
		id: 2,
		telegramMessageId: null,
		telegramGroupId: 1,
		cityId: 1,
		categoryId: 1,
		title: 'MacBook Air M2 2023',
		description: 'MacBook Air M2, 8GB RAM, 256GB SSD, цвет Midnight. Б/у 6 месяцев, батарея 97%. Без царапин и сколов.',
		price: '3200.00',
		currency: 'GEL',
		contact: '@macbook_seller',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=MacBook+Air+M2'],
		status: 'active',
		publishedAt: new Date(Date.now() - 5 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[0],
		category: mockCategories[0]
	},
	{
		id: 3,
		telegramMessageId: null,
		telegramGroupId: 1,
		cityId: 1,
		categoryId: 2,
		title: 'Nike Air Max 90 (42 размер)',
		description: 'Кроссовки Nike Air Max 90, размер 42 EUR. Новые, в оригинальной коробке. Не подошёл размер.',
		price: '350.00',
		currency: 'GEL',
		contact: '@nike_seller',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=Nike+Air+Max'],
		status: 'active',
		publishedAt: new Date(Date.now() - 12 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[0],
		category: mockCategories[1]
	},
	{
		id: 4,
		telegramMessageId: null,
		telegramGroupId: 1,
		cityId: 1,
		categoryId: 3,
		title: 'Toyota Camry 2019, 2.5L',
		description: 'Toyota Camry 2019 года, пробег 45,000 км. Один владелец. Все ТО пройдены у официального дилера.',
		price: '58000.00',
		currency: 'GEL',
		contact: '@camry_seller',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=Toyota+Camry'],
		status: 'active',
		publishedAt: new Date(Date.now() - 24 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[0],
		category: mockCategories[2]
	},
	{
		id: 5,
		telegramMessageId: null,
		telegramGroupId: 1,
		cityId: 1,
		categoryId: 4,
		title: 'Диван угловой IKEA KIVIK',
		description: 'Угловой диван IKEA KIVIK, серый. Покупал 2 года назад. Состояние хорошее. Самовывоз из Сабуртало.',
		price: '1200.00',
		currency: 'GEL',
		contact: '@furniture_guy',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=IKEA+Sofa'],
		status: 'active',
		publishedAt: new Date(Date.now() - 48 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[0],
		category: mockCategories[3]
	},
	{
		id: 6,
		telegramMessageId: null,
		telegramGroupId: 2,
		cityId: 2,
		categoryId: 1,
		title: 'PlayStation 5 + 2 геймпада',
		description: 'PS5 с дисководом, 2 DualSense контроллера. 5 игр в комплекте: Spider-Man 2, God of War, FIFA 24.',
		price: '1800.00',
		currency: 'GEL',
		contact: '@ps5_batumi',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=PS5'],
		status: 'active',
		publishedAt: new Date(Date.now() - 3 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[1],
		category: mockCategories[0]
	},
	{
		id: 7,
		telegramMessageId: null,
		telegramGroupId: 2,
		cityId: 2,
		categoryId: 8,
		title: 'Велосипед горный Trek Marlin 7',
		description: 'Trek Marlin 7, рама L (19"), колёса 29". Гидравлические тормоза Shimano. Пробег ~500 км.',
		price: '2100.00',
		currency: 'GEL',
		contact: '@bike_batumi',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=Trek+Bike'],
		status: 'active',
		publishedAt: new Date(Date.now() - 6 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[1],
		category: mockCategories[7]
	},
	{
		id: 8,
		telegramMessageId: null,
		telegramGroupId: 1,
		cityId: 1,
		categoryId: 7,
		title: 'Коляска Cybex Priam 2024',
		description: 'Коляска Cybex Priam, цвет Deep Black. Полный комплект: люлька, прогулочный блок, адаптеры.',
		price: '1500.00',
		currency: 'GEL',
		contact: '@mom_selling',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=Cybex+Priam'],
		status: 'active',
		publishedAt: new Date(Date.now() - 8 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[0],
		category: mockCategories[6]
	},
	{
		id: 9,
		telegramMessageId: null,
		telegramGroupId: 2,
		cityId: 2,
		categoryId: 1,
		title: 'Samsung Galaxy S24 Ultra',
		description: 'Galaxy S24 Ultra 512GB, Titanium Black. Идеальное состояние. Полный комплект с чеком.',
		price: '3500.00',
		currency: 'GEL',
		contact: '@samsung_batumi',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=S24+Ultra'],
		status: 'active',
		publishedAt: new Date(Date.now() - 4 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[1],
		category: mockCategories[0]
	},
	{
		id: 10,
		telegramMessageId: null,
		telegramGroupId: 1,
		cityId: 1,
		categoryId: 6,
		title: 'Уроки английского онлайн',
		description: 'Преподаватель с сертификатом CELTA. Индивидуальные занятия по Zoom. Первый урок бесплатно!',
		price: '40.00',
		currency: 'GEL',
		contact: '@english_teacher_ge',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=English+Lessons'],
		status: 'active',
		publishedAt: new Date(Date.now() - 1 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[0],
		category: mockCategories[5]
	},
	{
		id: 11,
		telegramMessageId: null,
		telegramGroupId: 2,
		cityId: 2,
		categoryId: 2,
		title: 'Зимняя куртка Columbia XL',
		description: 'Мужская зимняя куртка Columbia Omni-Heat, размер XL. Носил один сезон. Очень тёплая.',
		price: '280.00',
		currency: 'GEL',
		contact: '@jacket_seller',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=Columbia+Jacket'],
		status: 'active',
		publishedAt: new Date(Date.now() - 72 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[1],
		category: mockCategories[1]
	},
	{
		id: 12,
		telegramMessageId: null,
		telegramGroupId: 1,
		cityId: 1,
		categoryId: 4,
		title: 'Стол письменный дубовый',
		description: 'Письменный стол из массива дуба. 140x70 см. Ручная работа. Два выдвижных ящика. Доставка по Тбилиси.',
		price: '900.00',
		currency: 'GEL',
		contact: '@wood_master',
		images: ['https://placehold.co/600x400/1a1a2e/e0e0e0?text=Oak+Desk'],
		status: 'active',
		publishedAt: new Date(Date.now() - 36 * 3600_000),
		expiresAt: null,
		createdAt: new Date(),
		city: mockCities[0],
		category: mockCategories[3]
	}
];
